<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <!-- Базовая модель Maven -->
  <modelVersion>4.0.0</modelVersion>

  <!-- Координаты проекта -->
  <groupId>com.demoqa</groupId>
  <artifactId>DemoQA_POM_QA70</artifactId>
  <version>1.0-SNAPSHOT</version>

  <!-- Настройки компилятора -->
  <properties>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <!-- Зависимости проекта -->
  <dependencies>

    <!-- Selenium WebDriver -->
    <dependency>
      <groupId>org.seleniumhq.selenium</groupId>
      <artifactId>selenium-java</artifactId>
      <version>4.36.0</version>
    </dependency>

    <!-- JUnit 5 (Jupiter API + Engine) -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <version>5.10.1</version>
    </dependency>

    <!-- WebDriverManager (авто-менеджер драйверов браузеров) -->
    <dependency>
      <groupId>io.github.bonigarcia</groupId>
      <artifactId>webdrivermanager</artifactId>
      <version>5.7.0</version>
    </dependency>

    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
      <version>7.1.0</version>
      <scope>test</scope>
    </dependency>


    <!-- Logback: логирование (logger.info / error и т.п.) -->
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.5.19</version>
    </dependency>

    <!-- AssertJ: fluent-assertions + SoftAssertions -->
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.27.3</version>
    </dependency>

  </dependencies>

  <!-- Настройка сборки и плагинов -->
  <build>
    <plugins>

      <!-- Maven Surefire Plugin:
           запускает все тесты, оканчивающиеся на *Tests.java -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>3.2.5</version>
        <configuration>
          <includes>
            <include>**/*Tests.java</include>
          </includes>
        </configuration>
      </plugin>

    </plugins>
  </build>

</project>